---
# tasks file for confluence

- name: stop service if upgrade
  service: name=confluence state=stopped
  when: confluence_upgrade == true
  notify: restart confluence
  tags: confluence

- name: remove legacy binary if upgrade
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ confluence_catalina }}", owner: "{{ confluence_user }}", group: "{{ confluence_user }}", mode: '0755', state: 'absent' }
  when: confluence_upgrade == true
  notify: restart confluence
  tags: confluence

- name: create system user
  user:
    name={{ confluence_user }}
    password={{ confluence_pass }}
    home={{ confluence_home }}
    system=yes
    shell=/bin/bash
  notify: restart confluence
  tags: confluence

- name: prepare files
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ confluence_catalina }}", owner: "{{ confluence_user }}", group: "{{ confluence_user }}", mode: '0755', state: 'directory' }
  notify: restart confluence
  tags: confluence

- name: download package
  get_url:
    url={{ confluence_url }}
    dest={{ confluence_archive }}
    sha256sum={{ confluence_sha256 }}
  notify: restart confluence
  tags: confluence

- name: unarchive package
  shell: tar zxvf {{ confluence_archive }} -C {{ confluence_catalina }} --strip-components=1; chown -Rf {{ confluence_user }}:{{ confluence_user }} {{ confluence_catalina }}
  args:
    creates: "{{ confluence_catalina }}/bin/start-confluence.sh"
  notify: restart confluence
  tags: confluence

- name: copy templates
  template:
    src="{{ item.template }}.j2"
    dest="/{{ item.template }}"
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { template: 'etc/init.d/confluence', owner: 'root', group: 'root', mode: '0755' }
    - { template: 'usr/share/confluence/bin/setenv.sh', owner: "{{ confluence_user }}", group: "{{ confluence_user }}", mode: '0644' }
    - { template: 'usr/share/confluence/conf/server.xml', owner: "{{ confluence_user }}", group: "{{ confluence_user }}", mode: '0644' }
  notify: restart confluence
  tags: confluence

- name: enable service
  service: name=confluence enabled=yes
  notify: restart confluence
  tags: confluence
