---
# tasks file for hswong3i.confluence

- name: stop service if upgrade
  service: name=confluence state=stopped
  when: confluence_upgrade == true
  notify: restart confluence
  tags: hswong3i.confluence

- name: remove legacy binary if upgrade
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ confluence_catalina }}", owner: "{{ confluence_user }}", group: "{{ confluence_user }}", mode: '0755', state: 'absent' }
  when: confluence_upgrade == true
  notify: restart confluence
  tags: hswong3i.confluence

- name: apt-get install
  apt:
    name={{ item.name }}
    state={{ item.state }}
  with_items:
    - { name: 'ufw', state: 'latest' }
  notify: restart confluence
  tags: hswong3i.confluence

- name: create user
  user:
    name={{ confluence_user }}
    password={{ confluence_pass | password_hash('sha512', confluence_hash_salt) }}
    home={{ confluence_home }}
    shell=/bin/bash
  notify: restart confluence
  tags: hswong3i.confluence

- name: prepare files
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ confluence_catalina }}", owner: "{{ confluence_user }}", group: "{{ confluence_user }}", mode: '0755', state: 'directory' }
  notify: restart confluence
  tags: hswong3i.confluence

- name: download package
  get_url:
    url={{ confluence_url }}
    dest={{ confluence_archive }}
    sha256sum={{ confluence_sha256 }}
  notify: restart confluence
  tags: hswong3i.confluence

- name: unarchive package
  shell: tar zxvf {{ confluence_archive }} -C {{ confluence_catalina }} --strip-components=1; chown -Rf {{ confluence_user }}:{{ confluence_user }} {{ confluence_catalina }}
  args:
    creates: "{{ confluence_catalina }}/bin/start-confluence.sh"
  notify: restart confluence
  tags: hswong3i.confluence

- name: copy templates
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: 'etc/init.d/confluence.j2', dest: '/etc/init.d/confluence', owner: 'root', group: 'root', mode: '0755' }
    - { src: 'usr/share/confluence/bin/setenv.sh.j2', dest: "{{ confluence_catalina }}/bin/setenv.sh", owner: "{{ confluence_user }}", group: "{{ confluence_user }}", mode: '0644' }
    - { src: 'usr/share/confluence/conf/server.xml.j2', dest: "{{ confluence_catalina }}/conf/server.xml", owner: "{{ confluence_user }}", group: "{{ confluence_user }}", mode: '0644' }
  notify: restart confluence
  tags: hswong3i.confluence

- name: enable service
  service: name=confluence enabled=yes
  notify: restart confluence
  tags: hswong3i.confluence

- name: enable incomming connection
  ufw:
    to_port={{ item.to_port }}
    proto={{ item.proto }}
    rule={{ item.rule }}
  with_items:
    - { to_port: "{{ confluence_connector_port }}", proto: 'tcp', rule: 'allow' }
    - { to_port: "{{ confluence_server_port }}", proto: 'tcp', rule: 'allow' }
  notify: restart confluence
  tags: hswong3i.confluence
